ДЗ 5
dvalentina/2019-2-Track-Frontend-V-Danilova pull request #5
Opened 2019-12-05 01:03 UTC by dvalentina

# Домашнее задание №5

Прошу @martinkomitsky, @chexex или @priver проверить его.

Что было сделано:
* Компоненты переписаны на React;
* Восстановлены стили для всех компонентов;
* Восстановлена функциональность всех компонентов.

2019-12-05 06:09 UTC, martinkomitsky requested changes
![image](https://user-images.githubusercontent.com/14847018/70208452-aca30f00-173e-11ea-81ab-e63f74709801.png)
Почему никто не следит за тем, что сдает? Мы тоже можем игнорировать pull реквесты и не проверять их.

Было сказано проверять то, что студент сдает, самостоятельно. Деплой не выполнен.

2019-12-06 01:14 UTC, dvalentina commented
Здравствуйте!

Простите, пожалуйста, за сложившуюся ситуацию, в тот раз действительно невнимательно проверила, что отправляю в pr (оказалось, что я забыла закоммитить большую часть изменённых файлов).
Исправляюсь.

2019-12-06 04:38 UTC, martinkomitsky requested changes
OK, спасибо, что починила и задеплоила ДЗ.
Теперь по правкам:
![image](https://user-images.githubusercontent.com/14847018/70296336-4c25d780-17fb-11ea-8bcb-88603302fed0.png)
Вот эту строчку (preventDefault) нужно выполнять в первую очередь, иначе сейчас есть проблема: если отправить пустое сообщение, происходит отправка пустой формы и перезагрузка страницы.

2019-12-06 10:22 UTC, dvalentina commented
Проблема исправлена, теперь страница не перезагружается.

2019-12-09 04:10 UTC, martinkomitsky approved these changes
ок, 10!

2019-12-09 04:10 UTC, merged